### ISSUE TITLE
micro optimisation?

### ISSUE THREAD

**Issue by tonno** [subh83/RSJP-cpp#7]
I tried changing the access operator
  RSJresource& RSJresource::operator[] (std::string key)
to
  RSJresource& RSJresource::operator[] (const std::string& key)

I believe that some string creation and copying is now left out? Nothing seems to have broken, at least not on my tests.

Cheers
tommi.joutsiniemi@toistaiseksi.fi

**Comment by subh83** [comment]
sure. For small inputs (such as key-name), passing by reference may not make too much of a performance improvement and is typically considered optional. But if you are accessing operator[] a lot, and with long key-names, this may indeed make some performance difference.
